name: affective
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.5
  - notebook=6.4.3
  - jupyter=1.0.0
  - pandas=1.4.1
  - numpy=1.21.5
  - scikit-learn=1.0.2
  - matplotlib=3.5.2
  - torchvision=0.12.0
  