name: stat
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.5
  - notebook=6.4.3
  - numpy=1.20.3
  - matplotlib=3.4.2
  - networkx=2.6.2
  - jupyter=1.0.0
  - pandas=1.4.1
  - scipy=1.7.3
  - scikit-learn=1.0.2
  - seaborn=0.11.2
  - statsmodels=0.13.2
  - pyppeteer=1.0.2
  - altair=4.2.0